"""
Diagnoser — classifies the root cause of each failed payment.

Two-path architecture:
1. Deterministic Classifier (~80% of cases):
   - Direct lookup table: (error_code, error_reason) → RootCause
   - Confidence = 1.0, zero latency, fully auditable

2. AI-Augmented Classifier (~20% of cases):
   - Triggered when error_reason is unmapped, ambiguous, or compound
   - Calls llm.diagnose_ambiguous() with error payload context
   - If AI confidence < 0.7 → defaults to UNKNOWN (conservative escalation)

Every diagnosis is logged to the audit trail with method + reasoning.
"""

import sqlite3
from typing import Optional

from database.db import update_case
from models.enums import RootCause, RecoveryStatus, AuditEventType, Actor
from engine.audit import log_event, log_state_change
from ai import llm


# ─── Deterministic Lookup Table ────────────────────────────────────────────────
# Maps (error_reason) → RootCause for known Razorpay error payloads.
# This covers all 9 standard failure types generated by our batch data.
# Source truth: Razorpay payment error documentation + our error templates.

DETERMINISTIC_MAP: dict[str, RootCause] = {
    # Insufficient Funds
    "insufficient_funds": RootCause.INSUFFICIENT_FUNDS,

    # Expired Card
    "card_expired": RootCause.EXPIRED_CARD,

    # Bank Decline (generic)
    "payment_declined": RootCause.BANK_DECLINE,

    # Authentication Required
    "payment_requires_action": RootCause.AUTH_REQUIRED,

    # Network / Gateway Errors
    "request_timeout": RootCause.NETWORK_ERROR,
    "gateway_timeout": RootCause.NETWORK_ERROR,
    "gateway_error": RootCause.NETWORK_ERROR,

    # Account Closed
    "account_closed": RootCause.ACCOUNT_CLOSED,

    # International Restrictions
    "international_transaction_not_allowed": RootCause.INTERNATIONAL_RESTRICTION,

    # Fraud
    "suspected_fraud": RootCause.FRAUD_FLAG,
    "risk_check_failed": RootCause.FRAUD_FLAG,

    # Disputes / Chargebacks
    "payment_disputed": RootCause.DISPUTED,
    "chargeback_initiated": RootCause.DISPUTED,
}

# Secondary lookup by (error_code, error_source) for edge cases
# where error_reason alone is ambiguous
SECONDARY_MAP: dict[tuple[str, str], RootCause] = {
    ("GATEWAY_ERROR", "internal"): RootCause.NETWORK_ERROR,
    ("GATEWAY_ERROR", "bank"): RootCause.BANK_DECLINE,
}


def _deterministic_diagnose(
    error_code: str,
    error_reason: str,
    error_source: str,
) -> Optional[tuple[RootCause, str]]:
    """
    Attempt deterministic root cause classification.

    Returns:
        (RootCause, reasoning_string) if matched, else None.
    """
    # Primary: direct error_reason lookup
    if error_reason in DETERMINISTIC_MAP:
        root_cause = DETERMINISTIC_MAP[error_reason]
        reasoning = (
            f"Deterministic match: error_reason='{error_reason}' "
            f"maps directly to root cause '{root_cause.value}'"
        )
        return root_cause, reasoning

    # Secondary: (error_code, error_source) combination
    key = (error_code, error_source)
    if key in SECONDARY_MAP:
        root_cause = SECONDARY_MAP[key]
        reasoning = (
            f"Secondary deterministic match: error_code='{error_code}' + "
            f"error_source='{error_source}' maps to root cause '{root_cause.value}'"
        )
        return root_cause, reasoning

    return None


def diagnose(
    conn: sqlite3.Connection,
    case: dict,
) -> dict:
    """
    Diagnose the root cause of a failed payment case.

    Process:
    1. Try deterministic classification first (fast, reliable)
    2. Fall back to AI classification for unmapped/ambiguous cases
    3. Update the case record with diagnosis results
    4. Log ROOT_CAUSE_DIAGNOSED to audit trail
    5. Transition case status: diagnosing → intervention_selected

    Args:
        conn: Active SQLite connection (caller manages commit).
        case: Enriched case dict from detector (must include error fields,
              subscription/customer details).

    Returns:
        Dict with {root_cause, confidence, reasoning, method}
    """
    case_id = case["id"]
    error_code = case.get("failure_error_code", "")
    error_description = case.get("failure_error_description", "")
    error_reason = case.get("failure_error_reason", "")
    error_source = case.get("failure_error_source", "")

    # ── Path 1: Deterministic Classification ──────────────────────────────
    deterministic_result = _deterministic_diagnose(error_code, error_reason, error_source)

    if deterministic_result:
        root_cause, reasoning = deterministic_result
        confidence = 1.0
        method = "deterministic"
    else:
        # ── Path 2: AI-Augmented Classification ──────────────────────────
        method = "ai"
        payment_history = (
            f"Customer: {case.get('customer_name', 'Unknown')}, "
            f"Plan: {case.get('plan_name', 'Unknown')}, "
            f"Amount: Rs {case.get('amount_at_risk', 0) / 100:,.0f}, "
            f"Billing: {case.get('billing_cycle', 'monthly')}"
        )

        ai_result = llm.diagnose_ambiguous(
            error_code=error_code,
            error_description=error_description,
            error_reason=error_reason,
            error_source=error_source,
            payment_history=payment_history,
        )

        ai_root_cause_str = ai_result.get("root_cause", "unknown")
        confidence = ai_result.get("confidence", 0.0)
        reasoning = ai_result.get("reasoning", "AI diagnosis with no reasoning provided")

        # Validate AI returned a valid RootCause enum value
        try:
            root_cause = RootCause(ai_root_cause_str)
        except ValueError:
            root_cause = RootCause.UNKNOWN
            confidence = 0.0
            reasoning = (
                f"AI returned invalid root cause '{ai_root_cause_str}'. "
                f"Defaulting to UNKNOWN for conservative handling."
            )

        # Conservative: if AI confidence is too low, default to UNKNOWN
        if confidence < 0.7:
            root_cause = RootCause.UNKNOWN
            reasoning = (
                f"AI confidence {confidence:.2f} below threshold (0.7). "
                f"Original AI diagnosis: '{ai_root_cause_str}'. "
                f"Defaulting to UNKNOWN for conservative escalation. "
                f"AI reasoning: {reasoning}"
            )

    # ── Update Case Record ────────────────────────────────────────────────
    update_case(conn, case_id, {
        "root_cause": root_cause.value,
        "diagnosis_confidence": confidence,
        "diagnosis_method": method,
        "status": RecoveryStatus.INTERVENTION_SELECTED.value,
    })

    # ── Audit: ROOT_CAUSE_DIAGNOSED ───────────────────────────────────────
    log_event(
        conn=conn,
        case_id=case_id,
        event_type=AuditEventType.ROOT_CAUSE_DIAGNOSED,
        actor=Actor.AI if method == "ai" else Actor.SYSTEM,
        details={
            "root_cause": root_cause.value,
            "confidence": confidence,
            "method": method,
            "error_code": error_code,
            "error_reason": error_reason,
            "error_source": error_source,
            "error_description": error_description[:200],  # Truncate for DB
        },
        reasoning=reasoning,
    )

    # ── Audit: State transition ───────────────────────────────────────────
    log_state_change(
        conn=conn,
        case_id=case_id,
        from_status=RecoveryStatus.DIAGNOSING.value,
        to_status=RecoveryStatus.INTERVENTION_SELECTED.value,
        reason=f"Root cause diagnosed: {root_cause.value} (confidence: {confidence})",
    )

    result = {
        "root_cause": root_cause,
        "confidence": confidence,
        "reasoning": reasoning,
        "method": method,
    }

    return result


def diagnose_batch(
    conn: sqlite3.Connection,
    cases: list[dict],
) -> dict:
    """
    Diagnose a batch of cases and return summary statistics.

    Args:
        conn: Active SQLite connection.
        cases: List of enriched case dicts from detector.

    Returns:
        Summary dict with counts by root cause, method stats, etc.
    """
    if not cases:
        print("ℹ️  No cases to diagnose.")
        return {"total": 0, "by_root_cause": {}, "by_method": {}}

    print(f"\n🧠 Diagnosing {len(cases)} cases...")

    by_root_cause: dict[str, int] = {}
    by_method: dict[str, int] = {"deterministic": 0, "ai": 0}
    ai_cases: list[str] = []

    for i, case in enumerate(cases, 1):
        result = diagnose(conn, case)
        rc_val = result["root_cause"].value
        method = result["method"]

        by_root_cause[rc_val] = by_root_cause.get(rc_val, 0) + 1
        by_method[method] = by_method.get(method, 0) + 1

        if method == "ai":
            ai_cases.append(case["id"])

        # Progress indicator every 10 cases
        if i % 10 == 0 or i == len(cases):
            print(f"  Diagnosed {i}/{len(cases)} cases...")

    conn.commit()

    # Print summary
    print(f"\n📊 Diagnosis complete:")
    print(f"  Deterministic: {by_method['deterministic']} cases")
    print(f"  AI-augmented:  {by_method['ai']} cases")
    print()
    print("  Root cause distribution:")
    for rc, count in sorted(by_root_cause.items(), key=lambda x: -x[1]):
        print(f"    {rc:30s} → {count} cases")

    if ai_cases:
        print(f"\n  ⚡ AI was called for cases: {', '.join(ai_cases)}")

    summary = {
        "total": len(cases),
        "by_root_cause": by_root_cause,
        "by_method": by_method,
        "ai_cases": ai_cases,
    }

    return summary
